import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: "#7D7D7D",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 40,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#F4F4F4",
  },
  backArrow: {
    padding: 10,
    marginLeft: 10,
  },
  backIcon: {
    fontSize: 24,
    color: "#000000",
  },
  pageTitle: {
    flex: 1,
    textAlign: "center",
    fontSize: 25,
    fontWeight: "bold",
    color: "#C67C4E",
    fontFamily: "Sora",
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 100,
  },
  businessNameContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
    backgroundColor: "#FFF8F5",
    padding: 15,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#F0F0F0",
  },
  businessNameLabel: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#000000",
    marginRight: 10,
  },
  businessNameValue: {
    fontSize: 16,
    color: "#C67C4E",
    fontWeight: "bold",
  },
  section: {
    marginTop: 30,
    marginBottom: 25,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#000000",
    marginBottom: 10,
  },
  sectionSubtitle: {
    fontSize: 14,
    color: "#7D7D7D",
    marginBottom: 15,
  },
  // Banner styles
  bannerContainer: {
    height: 180,
    borderRadius: 10,
    overflow: "hidden",
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#F0F0F0",
    backgroundColor: "#F9F9F9",
  },
  bannerImage: {
    width: "100%",
    height: "100%",
  },
  bannerPlaceholder: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FFF8F5",
  },
  bannerPlaceholderText: {
    color: "#C67C4E",
    fontSize: 16,
    fontWeight: "500",
  },
  pointsConfigContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    padding: 15,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#F0F0F0",
  },
  pointsConfigLabel: {
    flex: 1,
    fontSize: 16,
    color: "#000000",
  },
  pointsInput: {
    width: 60,
    height: 40,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 8,
    textAlign: "center",
    fontSize: 16,
    color: "#000000",
    backgroundColor: "#FFFFFF",
  },
  tierCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#F0F0F0",
    padding: 15,
    marginBottom: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  tierHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#F4F4F4",
    paddingBottom: 10,
  },
  tierTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#000000",
  },
  removeButton: {
    padding: 5,
  },
  removeButtonText: {
    fontSize: 14,
    color: "#FF6B6B",
  },
  tierRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 15,
  },
  tierLabel: {
    fontSize: 14,
    color: "#000000",
    flex: 1,
  },
  tierInput: {
    flex: 1,
    height: 40,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 8,
    paddingHorizontal: 10,
    backgroundColor: "#FFFFFF",
  },
  addTierButton: {
    backgroundColor: "#FFF8F5",
    borderWidth: 1,
    borderColor: "#C67C4E",
    borderRadius: 10,
    padding: 15,
    alignItems: "center",
    marginTop: 10,
  },
  addTierButtonText: {
    color: "#C67C4E",
    fontSize: 16,
    fontWeight: "bold",
  },
  footer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#FFFFFF",
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: "#F4F4F4",
  },
  saveButton: {
    backgroundColor: "#C67C4E",
    borderRadius: 7,
    padding: 10,
    alignItems: "center",
  },
  saveButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  deleteImageButton: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: "rgba(0,0,0,0.5)",
    borderRadius: 20,
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
});

export default styles;
