import { StyleSheet } from 'react-native';
import { widthPercentageToDP as wp } from 'react-native-responsive-screen';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 0,
    paddingTop: -100,
    paddingBottom:-30,
    width: '100%', 
  },
  header: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: wp('0%'),
  },
  backButton: {
    position: 'absolute',
    left: wp('4%'),
    top: wp('5%'),
    zIndex: 10,
    padding: wp('2%'),
    borderRadius: wp('3%'),
    backgroundColor: '#ffffff',
  },
  backIcon: {
    width: 24,
    height: 24,
    resizeMode: 'contain',
  },
 
  
  shopName: {
    color: '#C67C4E',
    fontWeight: '800',
    textAlign: 'center',
    marginTop: wp('3%'),
    fontSize: wp('6.5%'),
    letterSpacing: 0.5,
    paddingTop:10,
    marginBottom:-40,
  },
  // --- Enhanced Rating & Reviews Section ---
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    borderRadius: wp('3%'),
    padding: wp('4%'),
    marginTop: wp('1%'),
    marginHorizontal: wp('4%'),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 4,
  },
  ratingText: {
    fontSize: wp('5.2%'),
    fontWeight: '700',
    color: '#2D2D2D',
    marginLeft: wp('2%'),
  },
  reviewsLink: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: wp('2.5%'),
    paddingHorizontal: wp('4.5%'),
    backgroundColor: '#C67C4E',
    borderRadius: wp('3%'),
    shadowColor: '#E27D19',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  reviewsLinkText: {
    fontSize: wp('4.8%'),
    color: '#fff',
    fontWeight: '600',
    marginRight: wp('1.5%'),
  },
  // --- Premium Location Section ---
  locationContainer: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: wp('4%'),
    marginVertical: wp('2.5%'),
    padding: wp('4%'),
    borderRadius: wp('3%'),
    borderLeftWidth: wp('1%'),
    borderLeftColor: '#E27D19',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  locationTitle: {
    fontSize: wp('4.8%'),
    fontWeight: '700',
    color: '#2D2D2D',
    marginBottom: wp('1.5%'),
    letterSpacing: 0.3,
  },
  shopDetailItem: {
    fontSize: wp('4.5%'),
    color: '#666',
    lineHeight: wp('5.5%'),
  },
  // --- Enhanced Hours Section ---
  hoursContainer: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: wp('4%'),
    marginVertical: wp('2.5%'),
    padding: wp('4%'),
    borderRadius: wp('3%'),
    borderLeftWidth: wp('1%'),
    borderLeftColor: '#4A90E2',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  hoursTitle: {
    fontSize: wp('4.8%'),
    fontWeight: '700',
    color: '#2D2D2D',
    marginBottom: wp('1.5%'),
    letterSpacing: 0.3,
  },
  hoursText: {
    fontSize: wp('4.5%'),
    color: '#666',
    lineHeight: wp('5.5%'),
  },
  // --- Menu Section Styling ---
  menuHeading: {
    marginTop: wp('6%'),
    marginHorizontal: wp('4%'),
    fontSize: wp('6%'),
    fontWeight: '800',
    color: '#2D2D2D',
    letterSpacing: 0.5,
  },
  scrollContainer: {
    paddingBottom: wp('15%'),
    paddingHorizontal: wp('2%'),
  },
  // --- Category Cards ---
  categoryContainer: {
    marginHorizontal: wp('3%'),
    marginVertical: wp('3%'),
    backgroundColor: '#FFFFFF',
    borderRadius: wp('3%'),
    padding: wp('4%'),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  categoryTitle: {
    fontSize: wp('5.5%'),
    fontWeight: '700',
    color: '#2D2D2D',
    marginBottom: wp('3%'),
    paddingBottom: wp('2%'),
    borderBottomWidth: 1,
    borderBottomColor: '#EEE',
  },
  // --- Menu Items ---
  menuCard: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: wp('3%'),
    backgroundColor: '#FFF',
    borderRadius: wp('3%'),
    padding: wp('3%'),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  menuContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  menuImage: {
    borderRadius: wp('3%'),
    marginRight: wp('4%'),
    width: wp('18%'),
    height: wp('18%'),
  },
  menuTextContainer: {
    flex: 1,
    marginLeft: 0,
  },
  menuTitle: {
    fontSize: wp('4.8%'),
    fontWeight: '600',
    color: '#2D2D2D',
    marginBottom: wp('0.5%'),
  },
  menuPrice: {
    fontSize: wp('4.5%'),
    color: '#C67C4E',
    fontWeight: '700',
  },
  addButton: {
    backgroundColor: '#C67C4E',
    padding: wp('3%'),
    borderRadius: wp('3%'),
    shadowColor: '#C67C4E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  addButtonText: {
    fontSize: wp('5.5%'),
    color: '#fff',
    fontWeight: '600',
    includeFontPadding: false,
  },
  noMenuContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  noMenuText: {
    fontSize: wp('5%'),
    fontWeight: 'bold',
    marginBottom: 10,
  },
  noMenuSubText: {
    fontSize: wp('4%'),
    color: 'gray',
    textAlign: 'center',
  },
});

export default styles;